### ISSUE TITLE
Configuration improvements

### ISSUE THREAD

**Issue by boltomli** [pviotti/sayit#31]
Thanks for creating such a nice piece of tool!

I'm now using it on my arch linux box, but found a few configuration issues that might need document update.

1. I input a key from my Cognitive Service resource to make it work. It seems subscription ID is not necessary and it won't work. So perhaps the hint and the comment in config file should be updated?
1. Output is limited to 16kHz MP3, it's fine, but neural voices support 24kHz PCM that is obviously better to hear.

**Comment by pviotti** [comment]
Thanks (and sorry for the delay, I didn't receive any notification for this issue..).
I'll look into this and release a new version hopefully in the next few days.

**Comment by pviotti** [comment]
The fixes have been released in v1.0 (available also as Arch Linux package) - [here](https://github.com/pviotti/sayit/releases/tag/v1.0) is the changelog.
